package GUI.components.item;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JCheckBox;
import javax.swing.JPanel;

import com.chat.Member;

import GUI.components.item.ItemMember.IIemMemberListener;

public class ItemAddUser extends JPanel {

    private Member mMember;
    private final IIemMemberListener mListener;

    /**
     * Creates new form NewJPanel
     */
    public ItemAddUser(Member member, IIemMemberListener listener) {
        mListener = listener;
        mMember = member;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mCkBox = new javax.swing.JCheckBox();
        mCkBox = new JCheckBox();
        mCkBox.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    mListener.addMember(mMember);
                } else {
                    mListener.deleteMember(mMember);
                }
            }

        });
        mComboBox = new javax.swing.JComboBox<>();

        mCkBox.setText(mMember.getNick());

        mComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "REGULAR" }));

        if (mMember.isAdmin()) {
            mComboBox.setSelectedIndex(0);
        } else {
            mComboBox.setSelectedIndex(1);
        }

        mComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String selectedItem = (String) mComboBox.getSelectedItem();

                switch (selectedItem) {
                    case "ADMIN":
                        mMember.makeAdmin();
                        break;
                    case "REGULAR":
                        mMember.makeRegular();
                        break;
                    default:
                        mMember.makeRegular();
                        break;
                }
                mListener.editRights(mMember);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mCkBox)
                                .addGap(18, 18, 18)
                                .addComponent(mComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(212, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mCkBox)
                                        .addComponent(mComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JCheckBox mCkBox;
    private javax.swing.JComboBox<String> mComboBox;
    // End of variables declaration
}
