package GUI.components;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JDialog;

import com.chat.Chat;
import com.chat.Member;

import GUI.SwingUtils;
import GUI.components.item.ItemAddUser;
import GUI.components.item.ItemMember.IIemMemberListener;
import GUI.components.panels.PList;

public class MyDialog extends JDialog {

    public static MyDialog selectUsers(java.awt.Frame parent, boolean modal, Chat curretnChat, List<String> userList) {
        return new MyDialog(parent, modal, curretnChat, userList, false);
    }

    public static MyDialog manageMembers(java.awt.Frame parent, boolean modal, Chat curretnChat,
            List<String> userList) {
        return new MyDialog(parent, modal, curretnChat, userList, true);
    }

    private Chat mCandidate;
    private boolean editing;

    /**
     * Creates new form MyDialog
     */
    private MyDialog(java.awt.Frame parent, boolean modal, Chat curretnChat, List<String> userList, boolean isEditing) {
        super(parent, modal);
        mCandidate = curretnChat;
        editing = isEditing;
        initComponents(userList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(List<String> seluserList) {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mBtn = new javax.swing.JButton();
        mBtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                boolean confirm = SwingUtils.confrimDialog(null, "Save changes?");

            }

        });
        mContentPane = new PList();

        for (String string : seluserList) {
            System.out.println(string);
            Member iMember = Member.init(string, false);
            System.out.println(iMember.getReference());
            ItemAddUser itemMember = new ItemAddUser(iMember, iListener);
            mContentPane.addUserToSelect(itemMember);
        }

        mBtn.setText("mBtn");

        getContentPane().add(mContentPane, java.awt.BorderLayout.CENTER);
        getContentPane().add(mBtn, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JButton mBtn;
    private PList mContentPane;
    // End of variables declaration

    private final IIemMemberListener iListener = new IIemMemberListener() {

        @Override
        public void addMember(Member member) {
            mCandidate.addMember(member);
        }

        @Override
        public void deleteMember(Member member) {
            mCandidate.deleteMember(member);
        }

        @Override
        public void editRights(Member member) {
            mCandidate.updateMember(member);
        }

    };
}
