/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.view.components;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JCheckBox;
import javax.swing.JDialog;

import com.chat.Member;

import GUI.GUI;

/**
 *
 * @author carlos
 */
public class MyUserPicker extends JDialog {

    private final List<String> mSelUserList;

    /**
     * Creates new form NewJDialog
     */
    public MyUserPicker(java.awt.Frame parent, boolean modal, List<String> userOpList, String chatTitle,
            String chatDesc) {
        super(parent, modal);
        mSelUserList = new ArrayList<>();
        initComponents(userOpList, chatTitle, chatDesc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(List<String> userOpList, String chatTitle, String chatDesc) {

        btn_ok = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        checkBoxPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                GUI.getInstance().pClientCon.createNewChat(chatTitle, chatDesc, mSelUserList);
                dispose();

            }
        });

        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                dispose();
                
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_cancel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        234, Short.MAX_VALUE)
                                                .addComponent(btn_ok)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(checkBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_cancel)
                                        .addComponent(btn_ok))
                                .addContainerGap()));

        setUserOpList(userOpList);

        pack();
    }// </editor-fold>

    private void setUserOpList(List<String> userList) {
        for (String iter : userList) {
            JCheckBox ckIter = new JCheckBox(iter);
            checkBoxPanel.add(ckIter);
            ckIter.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {

                    String memberRef = iter + Member.SEPARATOR + "REG";

                    if (ckIter.isSelected()) {
                        mSelUserList.add(memberRef);
                    } else {
                        mSelUserList.remove(memberRef);
                    }

                    for (String string : mSelUserList) {
                        System.out.println("SEL" + string);
                    }
                }
            });
        }

        validate();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_ok;
    private javax.swing.JPanel checkBoxPanel;
    javax.swing.GroupLayout checkBoxPanelLayout;
    // End of variables declaration

    public interface IListener {
        void onOKClik(String chatTitle, String chatDesc);
    }
}
