/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI.view.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.DefaultListModel;

import com.chat.Chat;
import com.comunication.MSG;

import GUI.AppState;
import controller.manager.FileManager;

/**
 *
 * @author carlos
 */
public class ConversationPanel extends javax.swing.JPanel {

	private boolean isChat = false;
	private IChatLListener iChatListener;
	public DefaultListModel<String> msgListModel = new DefaultListModel<String>();

	public String title;
	public String id;

	/**
	 * Creates new form NewJPanel
	 */
	public ConversationPanel() {
		super();
	}

	public ConversationPanel(Chat chat, IChatLListener listener) {
		isChat = true;
		iChatListener = listener;
		initComponents(chat.getTitle(), chat.getDescription());
	}

	public ConversationPanel(String convId, String convTitle, IChatLListener listener) {
		isChat = false;
		iChatListener = listener;
		id = convId;
		title = convTitle;
		initComponents(convId, convTitle);
	}

	public void addLine(String line) {
		msgListModel.addElement(line);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents(String receptorId, String receptorNick) {

		FileManager.getInstance().initHistoryFile(id, title);

		ArrayList<String> lines = FileManager.getInstance().loadHistory();
		for (String line : lines) {
			addLine(line);
		}

		jScrollPane1 = new javax.swing.JScrollPane();
		jMessages = new javax.swing.JList<>(msgListModel);
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(325, 400));
		setPreferredSize(new java.awt.Dimension(325, 400));

		jMessages.removeAll();
		jScrollPane1.setViewportView(jMessages);

		jScrollPane2.setViewportView(jTextPane1);

		jButton1.setText("SEND");
		jButton1.setAlignmentX(0.5F);
		jButton1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent arg0) {
				actionSend();
			}

		});

		jLabel2.setIcon(new javax.swing.ImageIcon("/home/carlos/Desktop/rawIcons/btn_copy_to_clipboard.png")); // NOI18N
		jLabel2.setText(receptorNick);
		jLabel2.setAlignmentX(0.5F);
		jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
		jLabel2.setMaximumSize(new java.awt.Dimension(64, 256));
		jLabel2.setMinimumSize(new java.awt.Dimension(32, 64));
		jLabel2.setRequestFocusEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jScrollPane1)
														.addGroup(layout.createSequentialGroup()
																.addComponent(jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(jScrollPane2)))
												.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 179,
														Short.MAX_VALUE)
												.addGap(140, 140, 140)))));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jButton1))
								.addContainerGap()));
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JList<String> jMessages;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextPane jTextPane1;
	// End of variables declaration

	private void actionSend() {
		try {

			String text = jTextPane1.getText();

			AppState.getInstance().pClientCon.sendToSingleReq(id, title, text);

			DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
			LocalDateTime now = LocalDateTime.now();

			iChatListener.onMessageSent(AppState.getInstance().pClientCon.getNick(), dtf.format(now), text,
					msgListModel);

		} catch (NullPointerException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public interface IChatLListener {
		void onMessageRecieved(MSG msgReceived);

		void onMessageRead();

		void onMessageSent(String nick, String dateTime, String text, DefaultListModel<String> listModel);

		void onMessageWritten();
	}
}
