package GUI.view.panels;

import javax.swing.JLabel;
import javax.swing.JPanel;

import GUI.view.components.ImageView;

public class ProfilePanel extends JPanel {

    public ProfilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        canvas1 = new ImageView();

        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(canvas1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        139,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        107,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        78,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(canvas1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        136,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel1,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        26,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(154, Short.MAX_VALUE)));

    }// </editor-fold>

    // Variables declaration - do not modify
    private ImageView canvas1;
    private JLabel jLabel1;
    // End of variables declaration

}
