/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package GUI.components.panels;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.swing.DefaultListModel;

import com.chat.Chat;
import com.data.MSG;

import GUI.GUI;

/**
 *
 * @author carlos
 */
public abstract class PConv extends javax.swing.JPanel {

	protected enum Type {
		CHAT("chat"),
		SINGLE("single");

		Type(String type) {

		}
	}

	/* STATIC */
	public static PSingle createSingleConv(String convId, String convTitle, String convSubTitle,
			IConvListener listener) {
		return new PSingle(convId, convTitle, convSubTitle, listener);
	}

	public static PChat createChatInstance(Chat chat, IConvListener listener) {
		return new PChat(chat, listener);
	}

	/* PROPs */
	protected volatile List<String> history;
	protected volatile DefaultListModel<String> mMsgListModel = new DefaultListModel<String>();
	protected String mTitle;
	protected String mSubTitle;
	protected String mId;
	protected boolean mOpen = false;

	protected IConvListener iConvListener;

	public String getTitle() {
		return mTitle;
	}

	public void setTitle(String newTitle) {
		mTitle = newTitle;
		mLabel0.setText(mTitle + mSubTitle);
	}

	public void setSubTitle(String newDesc) {
		mSubTitle = newDesc;
		mLabel0.setText(mTitle + mSubTitle);
	}

	public boolean isOpen() {
		return mOpen;
	}

	public void setState(boolean open) {
		mOpen = open;
	}

	/**
	 * The conversation's id can be a Chat id or a connection id
	 * 
	 * @return
	 */
	public String getConvId() {
		return mId;
	}

	public void requested() {
		requestFocus();
		mTxtPane.requestFocusInWindow();
	}

	public synchronized void addLine(String line) {
		mMsgListModel.addElement(line);
		// FileManager.getInstance().saveConvHistory(mTitle, line, mIsChat);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	protected void initComponents() {

		mScrollPane0 = new javax.swing.JScrollPane();
		mList = new javax.swing.JList<>(mMsgListModel);
		mScrollPane1 = new javax.swing.JScrollPane();
		mTxtPane = new javax.swing.JTextPane();
		mBtnSend = new javax.swing.JButton();
		mLabel0 = new javax.swing.JLabel();

		setMinimumSize(new java.awt.Dimension(325, 400));
		setPreferredSize(new java.awt.Dimension(325, 400));

		mList.removeAll();
		mScrollPane0.setViewportView(mList);

		mScrollPane1.setViewportView(mTxtPane);

		mBtnSend.setText("SEND");
		mBtnSend.addActionListener(arg0 -> {
			String text = mTxtPane.getText();

			DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
			LocalDateTime now = LocalDateTime.now();

			String line = "[" + dtf.format(now) + "]" + GUI.getInstance().getSession().getNick() + ": " + text;

			actionSend(line);
		});

		mLabel0.setIcon(new javax.swing.ImageIcon("/home/carlos/Desktop/rawIcons/btn_copy_to_clipboard.png")); // NOI18N
		mLabel0.setText(mTitle + "\n" + mSubTitle);
		mLabel0.setAlignmentX(0.5F);
		mLabel0.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
		mLabel0.setMaximumSize(new java.awt.Dimension(64, 256));
		mLabel0.setMinimumSize(new java.awt.Dimension(32, 64));
		mLabel0.setRequestFocusEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(mScrollPane0)
														.addGroup(layout.createSequentialGroup()
																.addComponent(mBtnSend)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(mScrollPane1)))
												.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addComponent(mLabel0, javax.swing.GroupLayout.DEFAULT_SIZE, 179,
														Short.MAX_VALUE)
												.addGap(140, 140, 140)))));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(mLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(mScrollPane0, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(mScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(mBtnSend))
								.addContainerGap()));

		addFocusListener(new FocusListener() {

			@Override
			public void focusGained(FocusEvent e) {
				requested();
			}

			@Override
			public void focusLost(FocusEvent e) {
			}

		});

	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton mBtnSend;
	private javax.swing.JLabel mLabel0;
	private javax.swing.JList<String> mList;
	private javax.swing.JScrollPane mScrollPane0;
	private javax.swing.JScrollPane mScrollPane1;
	private javax.swing.JTextPane mTxtPane;
	// End of variables declaration

	protected void actionSend(String line) {

		addLine("(you)" + line);
		mTxtPane.setText("");

	}

	protected void loadHistory() {
		for (String string : history) {
			addLine(string);
		}
	}

	public interface IConvListener {
		void onMsgSent(String convId, String convTitle, String convSubTitle, String line, boolean isChat);

		void onMsgRecieved(MSG msgReceived, boolean isChat);
	}

}
